### ISSUE TITLE
WML issues on Mountains of Doom

### ISSUE THREAD

**Issue by Jordy-Jordan** [TeamSurvivalXtreme/SXCollection#35]
WML warning at the preload
Then I noticed someone complaining about lua bugs

**Comment by stevecotton** [comment]
The WML warning

    Invalid WML found: [race] '' is missing a plural_name field.[race] '' is missing a plural_name field.[race] '' is missing a plural_name field.[race] '' is missing a plural_name field.[event] is missing name or id field

seems to be caused by having an `[event]` without a `name=`, it's between the `turn 80` event and the `turn 110` event. I have no idea how the warning is connected to the cause though. Wmllint doesn't notice this (which surprises me).

No idea about the Lua warning, could it have been from Ageless?

**Comment by Jordy-Jordan** [comment]
Could be
